#!/usr/bin/env node
import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const cli = path.join(root, 'bin', 'stackmind.js');

function run(args, cwd = root) {
  const res = spawnSync(process.execPath, [cli, ...args], {
    cwd,
    encoding: 'utf8',
  });
  if (res.status !== 0) {
    console.error(res.stdout);
    console.error(res.stderr);
    process.exit(res.status || 1);
  }
  return res.stdout;
}

function runNode(scriptPath, cwd) {
  const res = spawnSync(process.execPath, [scriptPath], { cwd, encoding: 'utf8' });
  if (res.status !== 0) {
    console.error(res.stdout);
    console.error(res.stderr);
    process.exit(res.status || 1);
  }
  console.log(res.stdout.trim());
}

function mustExist(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`[demo_proof] missing: ${filePath}`);
    process.exit(1);
  }
}

console.log('[demo_proof] doctor (repo)');
run(['doctor', root]);

const stacks = ['nextjs', 'python', 'nestjs', 'vue_nuxt'];
for (const stack of stacks) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), `stackmind_proof_${stack}_`));
  console.log(`[demo_proof] init ${stack} -> ${tmp}`);
  run(['init', stack, tmp, '--force']);
  mustExist(path.join(tmp, 'AGENTS.md'));
  mustExist(path.join(tmp, '.claude', 'CLAUDE.md'));
}

const liveTargets = [
  ['nextjs', 'examples/nextjs_live'],
  ['python', 'examples/python_live'],
  ['nestjs', 'examples/nestjs_live'],
  ['vue_nuxt', 'examples/vue_nuxt_live'],
];

for (const [stack, rel] of liveTargets) {
  const target = path.join(root, rel);
  console.log(`[demo_proof] init ${stack} into live sample ${rel}`);
  run(['init', stack, target, '--force']);
}

runNode(path.join(root, 'examples/nestjs_live/scripts/smoke.mjs'), path.join(root, 'examples/nestjs_live'));
runNode(path.join(root, 'examples/vue_nuxt_live/scripts/smoke.mjs'), path.join(root, 'examples/vue_nuxt_live'));
runNode(path.join(root, 'examples/nextjs_live/scripts/smoke.mjs'), path.join(root, 'examples/nextjs_live'));

const proofLog = [
  `# Proof log`,
  ``,
  `Generated by \`npm run demo_proof\`.`,
  ``,
  `- Kits: ${stacks.join(', ')}`,
  `- Live samples initialized and smoke-checked`,
  `- Timestamp: ${new Date().toISOString()}`,
  ``,
].join('\n');
fs.writeFileSync(path.join(root, 'docs/PROOF_LOG.md'), proofLog, 'utf8');

console.log('[demo_proof] passed');
