name: Slack Notify

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "${{ inputs.message }}"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "${{ inputs.message }}"
